syntax = "proto3";

option java_multiple_files = true;


package com.becker.freelance.component.prediction.backend.storage;


message GrpcUUID {
    string id = 1;
}

message GrpcApp {
    GrpcUUID id = 1;
    string app_name = 2;
}

message GrpcTag {
    GrpcUUID id = 1;
    string tag = 2;
}

message GrpcSourceMetadata {
    GrpcUUID id = 1;
    GrpcApp app = 2;
    string locale = 3;
    int64 version = 4;
    string created_at = 5;
    string last_modified_at = 6;
    repeated GrpcTag tags = 7;
    string file_name = 8;
    GrpcSourceMetadata parent = 9;
    bool hasChildren = 10;
}

message GrpcSourceMetadataList {
    repeated GrpcSourceMetadata metadata = 1;
}

message GrpcTagList {
    repeated GrpcTag tags = 1;
}

message GrpcAppList {
    repeated GrpcApp apps = 1;
}

message GrpcFloatArray {
    repeated float array = 1;
}

message GrpcSourceEmbedding {
    GrpcUUID metadata_id = 1;
    GrpcFloatArray embeddings = 2;
}