syntax = "proto3";

option java_multiple_files = true;


package com.becker.freelance.component.prediction.backend.storage;

import "com/becker/freelance/component/prediction/backend/storage/storagedto.proto";

service ApiSourceMetadataWriteRepository {
    rpc Save (GrpcSourceMetadata) returns (GrpcSourceMetadata);

}

service ApiTagsWriteRepository {
    rpc Save (GrpcTag) returns (GrpcTag);

}

service ApiAppsWriteRepository {

    rpc Save (GrpcApp) returns (GrpcApp);

}

service ApiEmbeddingWriteRepository {

    rpc Save (GrpcSourceEmbedding) returns (GrpcSourceMetadata);
}