grpc:
  client:
    backendStorageService:
      address: static://backend-storage-service:9090
      negotiationType: plaintext
    backendAppStorageService:
      address: static://backend-storage-service:9090
      negotiationType: plaintext
    backendTagStorageService:
      address: static://backend-storage-service:9090
      negotiationType: plaintext