syntax = "proto3";

option java_multiple_files = true;


package com.becker.freelance.component.prediction.backend.embedding;
import "google/protobuf/empty.proto";


message GrpcFloatArray {
    repeated float array = 1;
}

message GrpcEmbedding {
    GrpcFloatArray embeddings = 1;
}

message GrpcEmbeddingRequestChunk {
    bytes data = 1;
}

message GrpcPreferredChunkSize {
    int32 size = 1;
}


service ApiEmbeddingService {

    rpc PreferredChunkSize(google.protobuf.Empty) returns (GrpcPreferredChunkSize);

    rpc Embed (stream GrpcEmbeddingRequestChunk) returns (stream GrpcEmbedding);
}