syntax = "proto3";

option java_multiple_files = true;

package com.becker.freelance.component.prediction.backend.SourceContentExtraction;

import "google/protobuf/empty.proto";


message GrpcSourceContentExtractionUUID {
    string id = 1;
}

message GrpcSourceContentExtraction {
    string extract = 1;
}

message GrpcSourceContentExtractionRequestChunk {
    GrpcSourceContentExtractionUUID id = 1;
    bytes data = 2;
}

message GrpcSourceContentExtractionChunk {
    GrpcSourceContentExtractionUUID id = 1;
    string chunk = 2;
}

message GrpcSourceContentExtractionSupportsResponse {
    bool supports = 1;
}

message GrpcSourceContentExtractorId {
    string id = 1;
}

message GrpcGetLabelRequest {
    string identifier = 1;
}

message GrpcGetLabelResponse {
    string identifier = 1;
    string label = 2;
}

message GrpcSourceContentExtractionField {
    string id = 1;
    string type = 2;
    bool required = 3;
}

message GrpcSourceContentExtractionConfig {
    repeated GrpcSourceContentExtractionField fields = 1;
}

service ApiSourceContentExtractionService {
    rpc PrepareExtraction (google.protobuf.Empty) returns (GrpcSourceContentExtractionUUID);
    rpc Buffer (stream GrpcSourceContentExtractionRequestChunk) returns (google.protobuf.Empty);
    rpc SupportsOrReset(GrpcSourceContentExtractionUUID) returns (GrpcSourceContentExtractionSupportsResponse);
    rpc Extract(GrpcSourceContentExtractionUUID) returns (stream GrpcSourceContentExtractionChunk);
    rpc ClearBuffer(GrpcSourceContentExtractionUUID) returns (google.protobuf.Empty);
    rpc GetId(google.protobuf.Empty) returns (GrpcSourceContentExtractorId);
}

service ApiSourceContentExtractionLabelProvider {
    rpc GetLabel (GrpcGetLabelRequest) returns (GrpcGetLabelResponse);
    rpc GetId(google.protobuf.Empty) returns (GrpcSourceContentExtractorId);
}

service ApiSourceContentExtractionConfigProvider {
    rpc GetId(google.protobuf.Empty) returns (GrpcSourceContentExtractorId);
    rpc GetConfig (google.protobuf.Empty) returns (GrpcSourceContentExtractionConfig);
}