syntax = "proto3";

option java_multiple_files = true;


package com.becker.freelance.component.prediction.backend.ingest;

import "com/becker/freelance/component/prediction/backend/query/query.proto";

message GrpcIngestUUID {
    string id = 1;
}

message GrpcIngestApp {
    GrpcIngestUUID id = 1;
    string app_name = 2;
}

message GrpcIngestTag {
    GrpcIngestUUID id = 1;
    string tag = 2;
}

message GrpcIngestSourceMetadata {
    GrpcIngestUUID id = 1;
    GrpcIngestApp app = 2;
    int64 version = 3;
    string created_at = 4;
    string last_modified_at = 5;
    repeated GrpcIngestTag tags = 6;
    string file_name = 7;
    GrpcIngestSourceMetadata parent = 8;
    bool hasChildren = 9;
    string locale = 10;
}

message GrpcIngestSourceChunk {
    GrpcIngestUUID upload_id = 1;
    string file_name = 2;
    bytes data = 3;
}


service ApiSourceIngestRepository {
    rpc PrepareSave (GrpcIngestSourceMetadata) returns (GrpcIngestUUID);
    rpc HandleSave (stream GrpcIngestSourceChunk) returns (.com.becker.freelance.component.prediction.backend.query.GrpcQuerySourceMetadata);
}

service ApiTagsIngestRepository {
    rpc Save (GrpcIngestTag) returns (.com.becker.freelance.component.prediction.backend.query.GrpcQueryTag);

}

service ApiAppsIngestRepository {

    rpc Save (GrpcIngestApp) returns (.com.becker.freelance.component.prediction.backend.query.GrpcQueryApp);

}