syntax = "proto3";

option java_multiple_files = true;


package com.becker.freelance.component.prediction.backend.ingest;

import "com/becker/freelance/component/prediction/backend/query/query.proto";

message GrpcIngestUUID {
    string id = 1;
}

message GrpcIngestApp {
    GrpcIngestUUID id = 1;
    string app_name = 2;
}

message GrpcIngestTag {
    GrpcIngestUUID id = 1;
    string tag = 2;
}

message GrpcIngestDocumentMetadata {
    GrpcIngestUUID id = 1;
    GrpcIngestApp app = 2;
    string in_app_action_path = 3;
    string action_title = 4;
    string action_description = 5;
    string action_short_description = 6;
    int64 version = 7;
    string created_at = 8;
    string last_modified_at = 9;
    repeated GrpcIngestTag tags = 10;
}


service ApiDocumentMetadataIngestRepository {
    rpc Save (GrpcIngestDocumentMetadata) returns (.com.becker.freelance.component.prediction.backend.query.GrpcQueryDocumentMetadata);
}

service ApiTagsIngestRepository {
    rpc Save (GrpcIngestTag) returns (.com.becker.freelance.component.prediction.backend.query.GrpcQueryTag);

}

service ApiAppsIngestRepository {

    rpc Save (GrpcIngestApp) returns (.com.becker.freelance.component.prediction.backend.query.GrpcQueryApp);

}