syntax = "proto3";
option java_multiple_files = true;


package com.becker.freelance.component.prediction.backend.storage;

import "google/protobuf/empty.proto";


message GrpcApp {
    int64 id = 1;
    string app_name = 2;
}

message GrpcTag {
    int64 id = 1;
    string tag = 2;
}

message GrpcDocumentId {
    string document_id = 1;
}

message GrpcDocumentMetadata {
    int64 id = 1;
    GrpcDocumentId document_id = 2;
    GrpcApp app = 3;
    string in_app_action_path = 4;
    string action_title = 5;
    string action_description = 6;
    string action_short_description = 7;
    string locale = 8;
    int64 version = 9;
    string created_at = 10;
    repeated GrpcTag tags = 12;
}

message GrpcTagList {
    repeated GrpcTag tags = 1;
}


service ApiDocumentMetadataRepository {
    rpc Save (GrpcDocumentMetadata) returns (GrpcDocumentMetadata);

    rpc FindByRelatedDocumentId (GrpcDocumentId) returns (GrpcDocumentMetadata);
}

service ApiTagsRepository {
    rpc Save (GrpcTag) returns (GrpcTag);

    rpc FindAll (google.protobuf.Empty) returns (GrpcTagList);
}