syntax = "proto3";

option java_multiple_files = true;


package com.becker.freelance.component.prediction.backend.query;

import "google/protobuf/empty.proto";

message GrpcQueryUUID {
    string id = 1;
}

message GrpcQueryApp {
    GrpcQueryUUID id = 1;
    string app_name = 2;
}

message GrpcQueryTag {
    GrpcQueryUUID id = 1;
    string tag = 2;
}

message GrpcQuerySourceMetadata {
    GrpcQueryUUID id = 1;
    GrpcQueryApp app = 2;
    string locale = 3;
    int64 version = 4;
    string created_at = 5;
    string last_modified_at = 6;
    repeated GrpcQueryTag tags = 7;
    string file_name = 8;
    GrpcQuerySourceMetadata parent = 9;
    bool hasChildren = 10;
}

message GrpcQuerySourceMetadataList {
    repeated GrpcQuerySourceMetadata metadata = 1;
}

message GrpcQueryTagList {
    repeated GrpcQueryTag tags = 1;
}

message GrpcQueryAppList {
    repeated GrpcQueryApp apps = 1;
}


service ApiSourceMetadataReadRepository {

    rpc FindAll (google.protobuf.Empty) returns (GrpcQuerySourceMetadataList);

    rpc FindById (GrpcQueryUUID) returns (GrpcQuerySourceMetadata);
}

service ApiTagsReadRepository {

    rpc FindAll (google.protobuf.Empty) returns (GrpcQueryTagList);
}

service ApiAppsReadRepository {

    rpc FindAll (google.protobuf.Empty) returns (GrpcQueryAppList);
}