version: "3.9"
services:
  metadata-db:
    image: postgres:latest
    networks:
      - devnet
    volumes:
      - metadata-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  vector-db:
    image: qdrant/qdrant:latest
    networks:
      - devnet
    volumes:
      - vector-db-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage

  database-migration:
    image: beckerfreelancing/database-migration:${IMAGE_VERSION}
    build:
      context: ./../database-migration
      dockerfile: Dockerfile
    ports:
      - "5005:5005" # DEBUGGING
    depends_on:
      - metadata-db
    networks:
      - devnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_DATABASE_MIGRATION}

  backend-storage-service:
    image: beckerfreelancing/backend-storage-service:${IMAGE_VERSION}
    build:
      context: ./../backend/backend-storage-service
      dockerfile: Dockerfile
    depends_on:
      - metadata-db
      - database-migration
      - vector-db
    networks:
      - devnet

  backend-gateway:
    image: beckerfreelancing/backend-gateway:${IMAGE_VERSION}
    build:
      context: ./../backend/backend-gateway
      dockerfile: Dockerfile
    depends_on:
      - backend-storage-service
    networks:
      - devnet
    ports:
      - ${BACKEND_GATEWAY_PORT}:8080


networks:
  devnet:
    driver: bridge

volumes:
  metadata-db-data:
  vector-db-data: