version: "3.9"
services:
  metadata-db:
    image: postgres:latest
    networks:
      - devnet
    volumes:
      - metadata-db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  vector-db:
    image: qdrant/qdrant:latest
    networks:
      - devnet
    volumes:
      - vector-db-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__STORAGE_PATH=/qdrant/storage

  database-migration:
    image: beckerfreelancing/database-migration:${IMAGE_VERSION}
    ports:
      - "5005:5005" # DEBUGGING
    depends_on:
      - metadata-db
    networks:
      - devnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_DATABASE_MIGRATION} # DEBUGGING

  backend-storage-service:
    image: beckerfreelancing/backend-storage-service:${IMAGE_VERSION}
    ports:
      - "5006:5005" # DEBUGGING
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES}
      STORAGE_QDRANT_HOST: ${STORAGE_QDRANT_HOST}
      STORAGE_QDRANT_PORT: ${STORAGE_QDRANT_PORT}
      STORAGE_QDRANT_VECTORSIZE: ${STORAGE_QDRANT_VECTORSIZE}
      STORAGE_QDRANT_ONDISK: ${STORAGE_QDRANT_ONDISK}
      STORAGE_QDRANT_DISTANCE: ${STORAGE_QDRANT_DISTANCE}
      STORAGE_QDRANT_DATATYPE: ${STORAGE_QDRANT_DATATYPE}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_BACKEND_STORAGE_SERVICE} # DEBUGGING
    depends_on:
      - metadata-db
      - database-migration
      - vector-db
    networks:
      - devnet

  embedding-service:
    image: beckerfreelancing/backend-embedding-service:${IMAGE_VERSION}
    ports:
      - "5007:5005" # DEBUGGING
    environment:
      EMBEDDING_USE_L2_NORMALIZATION: ${EMBEDDING_USE_L2_NORMALIZATION}
      EMBEDDING_CHUNK_SIZE: ${EMBEDDING_CHUNK_SIZE}
      EMBEDDING_CHUNK_OVERLAP: ${EMBEDDING_CHUNK_OVERLAP}
      EMBEDDING_CHUNK_THRESHOLD: ${EMBEDDING_CHUNK_THRESHOLD}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_EMBEDDING} # DEBUGGING
    networks:
      - devnet

  language-service:
    image: beckerfreelancing/language-detection-service:${IMAGE_VERSION}
    ports:
      - "5008:5005" # DEBUGGING
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_LANGUAGE} # DEBUGGING
    networks:
      - devnet



  query-service:
    image: beckerfreelancing/backend-query-service:${IMAGE_VERSION}
    ports:
      - "5009:5005" # DEBUGGING
    environment:
      GRPC_CLIENT_BACKENDSTORAGEREADSERVICE_ADDRESS: static://backend-storage-service:9090
      GRPC_CLIENT_BACKENDSTORAGEREADSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDSTORAGEAPPREADSERVICE_ADDRESS: static://backend-storage-service:9090
      GRPC_CLIENT_BACKENDSTORAGEAPPREADSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDSTORAGETAGREADSERVICE_ADDRESS: static://backend-storage-service:9090
      GRPC_CLIENT_BACKENDSTORAGETAGREADSERVICE_NEGOTIATIONTYPE: plaintext
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_QUERY} # DEBUGGING
    depends_on:
      - backend-storage-service
    networks:
      - devnet

  source-extract-service-1:
    image: beckerfreelancing/backend-source-extraction-manual-input:${IMAGE_VERSION}
    environment:
      SERVICE_ID: source-extraction-manual-input
    networks:
      - devnet

  ingest-service:
    image: beckerfreelancing/backend-ingest-service:${IMAGE_VERSION}
    ports:
      - "5010:5005" # DEBUGGING
    environment:
      GRPC_CLIENT_BACKENDEMBEDDINGSERVICE_ADDRESS: static://embedding-service:9090
      GRPC_CLIENT_BACKENDEMBEDDINGSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_LANGUAGEDETECTIONSERVICE_ADDRESS: static://language-service:9090
      GRPC_CLIENT_LANGUAGEDETECTIONSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDAPPSTORAGESERVICE_ADDRESS: static://backend-storage-service:9090
      GRPC_CLIENT_BACKENDAPPSTORAGESERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDTAGSTORAGESERVICE_ADDRESS: static://backend-storage-service:9090
      GRPC_CLIENT_BACKENDTAGSTORAGESERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDDOCUMENTMETADATASTORAGESERVICE_ADDRESS: static://backend-storage-service:9090
      GRPC_CLIENT_BACKENDDOCUMENTMETADATASTORAGESERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDEMBEDDINGSTORAGESERVICE_ADDRESS: static://backend-storage-service:9090
      GRPC_CLIENT_BACKENDEMBEDDINGSTORAGESERVICE_NEGOTIATIONTYPE: plaintext
      SOURCEEXTRACTION_CONTENT_EXTRACTOR_SERVICE_PREFIX: ${SOURCE_EXTRACTION_SERVICE_PREFIX}
      SOURCEEXTRACTION_CONTENT_EXTRACTOR_SERVICE_GRPC_PORT: ${SOURCE_EXTRACTION_GRPC_PORT}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_INGEST} # DEBUGGING
    depends_on:
      - source-extract-service-1
      - embedding-service
      - backend-storage-service
      - language-service
      - query-service
    networks:
      - devnet


  backend-gateway:
    image: beckerfreelancing/backend-gateway:${IMAGE_VERSION}
    ports:
      - ${BACKEND_GATEWAY_PORT}:8080
      - "5011:5005" # DEBUGGING
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES}
      GRPC_CLIENT_BACKENDINGESTSERVICE_ADDRESS: static://ingest-service:9090
      GRPC_CLIENT_BACKENDINGESTSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDAPPINGESTSERVICE_ADDRESS: static://ingest-service:9090
      GRPC_CLIENT_BACKENDAPPINGESTSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDTAGINGESTSERVICE_ADDRESS: static://ingest-service:9090
      GRPC_CLIENT_BACKENDTAGINGESTSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDREADSERVICE_ADDRESS: static://query-service:9090
      GRPC_CLIENT_BACKENDREADSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDAPPREADSERVICE_ADDRESS: static://query-service:9090
      GRPC_CLIENT_BACKENDAPPREADSERVICE_NEGOTIATIONTYPE: plaintext
      GRPC_CLIENT_BACKENDTAGREADSERVICE_ADDRESS: static://query-service:9090
      GRPC_CLIENT_BACKENDTAGREADSERVICE_NEGOTIATIONTYPE: plaintext
      SOURCEEXTRACTION_CONTENT_EXTRACTOR_SERVICE_PREFIX: ${SOURCE_EXTRACTION_SERVICE_PREFIX}
      SOURCEEXTRACTION_CONTENT_EXTRACTOR_SERVICE_GRPC_PORT: ${SOURCE_EXTRACTION_GRPC_PORT}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS_BACKEND_GATEWAY} # DEBUGGING
    depends_on:
      - ingest-service
      - query-service
    networks:
      - devnet


networks:
  devnet:
    driver: bridge

volumes:
  metadata-db-data:
  vector-db-data: